# default configuration

app: "hetero_pos_neg_train" # hetero_pos_neg_train, partition_data
custom_note: "none"
dataset_name: "mind"
mind_version: "small"
dataset_dir: ../retexo-datasets
partition_dir: ../retexo-datasets/partitions/
partition_method: "random"
train_sampler: "MultiLayerFull"
part_obj: "vol"
num_partitions: 1
num_layers: 2
hidden_dim: 128
feat_hidden: 128
loss_func: 'log_sofmax'
num_rounds: [2000, 200, 200]
eval_after: 399
early_stop: 50
gnn_neg_ratio: 4
gnn_kl_weight: 0
local_epochs: 1
learning_rate: [1e-3, 1e-3, 1e-3]
momentum: 0.9
weight_decay: 0.0005
cross_score: false
dropout: 0
seed: 42
log_every: 50
best_val_model: true
node_rank: 0
parts_per_node: 4
device: "cuda"
measure_dv: false
sleep_time: 0.0
cache_size: 5
debug: true

quick_eval: true
gnn_quick_dev_reco: true
gnn_quick_dev_reco_size: 5000

dataset:
  download:
    dataset_name: ${dataset_name}
    dataset_dir: ${dataset_dir}
    add_self_loop: false

  partition:
    dataset_name: ${dataset_name}-${partition_method}-${part_obj}-${num_partitions}
    part_method: ${partition_method}
    num_parts: ${num_partitions}
    part_obj: ${part_obj}
    partition_dir: ${partition_dir}
  
  batching:
    batch_size: ${batch_size}
    shuffle: true
    num_workers: 4

model:
  _target_: models.gnn.SimpleGNN
  _recursive_: false
  hidden_dim: ${hidden_dim}
  n_layers: ${num_layers}
  dropout: ${dropout}
  conv_layer: 
    _target_: models.sage.CustomSAGEConv
    aggregator_type: "mean"

optimizer:
  _target_: torch.optim.Adam
  weight_decay: ${weight_decay}

distributed:
  backend: "gloo"
  init_method: "tcp://"
  master_addr: 127.0.0.1
  master_port: "10012"

task:
  _target_: tasks.node_classification.NodeClassificationTask