# default configuration

app: "train" # train, partition_data
dataset_name: "reddit"
dataset_dir: ../retexo-datasets/
partition_dir: ../retexo-datasets/partitions/
partition_method: "random"
part_obj: "vol"
num_partitions: 4
num_layers: 2
hidden_dim: 256
num_rounds: [200, 200, 200]
local_epochs: 1
learning_rate: [0.003, 0.003, 0.003]
momentum: 0.9
weight_decay: 0.0005
dropout: 0.3
seed: 42
log_every: 100
best_val_model: true
node_rank: 0
parts_per_node: 4
device: "cuda"
measure_dv: false
sleep_time: 0.0

dataset:
  download:
    dataset_name: ${dataset_name}
    dataset_dir: ${dataset_dir}
    add_self_loop: false

  partition:
    dataset_name: ${dataset_name}-${partition_method}-${part_obj}-${num_partitions}
    part_method: ${partition_method}
    num_parts: ${num_partitions}
    part_obj: ${part_obj}
    partition_dir: ${partition_dir}
  
  batching:
    batch_size: ${batch_size}
    shuffle: true
    num_workers: 4

model:
  _target_: models.gnn.SimpleGNN
  _recursive_: false
  hidden_dim: ${hidden_dim}
  n_layers: ${num_layers}
  dropout: ${dropout}
  conv_layer: 
    _target_: dgl.nn.GraphConv
    allow_zero_in_degree: true

optimizer:
  _target_: torch.optim.Adam
  weight_decay: ${weight_decay}

distributed:
  backend: "gloo"
  init_method: "tcp://"
  master_addr: 127.0.0.1
  master_port: "10011"

task:
  _target_: tasks.node_classification.NodeClassificationTask
